FROM maven:3.8.4-openjdk-11 AS builder

WORKDIR /app

COPY pom.xml .
COPY src ./src


RUN mvn clean package

FROM eclipse-temurin:11-jre-alpine

COPY --from=builder /app/target/*.jar /opt/app.jar
#COPY /app/target/classes/keys/private.ppk /opt/keys/private.ppk
#COPY /app/target/classes/keys/public.pub /opt/keys/public.pub

# Copy the resource files
COPY --from=builder /app/src/main/resources/keys /opt/keys

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/opt/app.jar"]